//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurssiSeuranta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KurssiRekisteriEntities : DbContext
    {
        public KurssiRekisteriEntities()
            : base("name=KurssiRekisteriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kurssi> Kurssi { get; set; }
        public virtual DbSet<Läsnäolotiedot> Läsnäolotiedot { get; set; }
        public virtual DbSet<Opettaja> Opettaja { get; set; }
        public virtual DbSet<OpetusTila> OpetusTila { get; set; }
        public virtual DbSet<Opiskelija> Opiskelija { get; set; }
    }
}
