//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurssiSeuranta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurssi
    {
        public string Kurssinimi { get; set; }
        public Nullable<int> Kurssikoodi { get; set; }
        public string Luokka { get; set; }
        public int KurssiID { get; set; }
        public Nullable<int> RekisteriID { get; set; }
        public Nullable<int> OpiskelijaID { get; set; }
    
        public virtual Opiskelija Opiskelija { get; set; }
        public virtual Lasnaolotiedot Lasnaolotiedot { get; set; }
    }
}
