//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurssiSeuranta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lasnaolotiedot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lasnaolotiedot()
        {
            this.Kurssi = new HashSet<Kurssi>();
        }
    
        public Nullable<System.DateTime> Kirjautuminen_sisaan { get; set; }
        public Nullable<System.DateTime> Kirjautuminen_ulos { get; set; }
        public Nullable<int> Luokkanumero { get; set; }
        public Nullable<int> OpettajaID { get; set; }
        public int RekisteriID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kurssi> Kurssi { get; set; }
        public virtual Opettaja Opettaja { get; set; }
    }
}
