//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurssiSeuranta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Läsnäolotiedot
    {
        public Nullable<System.DateTime> Kirjautuminen_sisään { get; set; }
        public Nullable<System.DateTime> Kirjautuminen_ulos { get; set; }
        public string Luokkanumero { get; set; }
        public int RekisteriID { get; set; }
        public Nullable<int> OpettajaID { get; set; }
        public Nullable<int> KurssiID { get; set; }
        public Nullable<int> OpiskelijaID { get; set; }
        public Nullable<int> LuokkaID { get; set; }
    
        public virtual Kurssi Kurssi { get; set; }
        public virtual OpetusTila OpetusTila { get; set; }
        public virtual Opettaja Opettaja { get; set; }
        public virtual Opiskelija Opiskelija { get; set; }
    }
}
