//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurssiSeuranta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpetusTila
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpetusTila()
        {
            this.Läsnäolotiedot = new HashSet<Läsnäolotiedot>();
        }
    
        public int LuokkaID { get; set; }
        public string LuokanNimi { get; set; }
        public string LuokkaKoodi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Läsnäolotiedot> Läsnäolotiedot { get; set; }
    }
}
